package sqlite

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"strconv"
	"strings"
	"time"

	errx "github.com/liuxb99/pcces-web/pcces-go/internal/platform/errors"
)

type ExecutionRepository struct{ store *Store }
func NewExecutionRepository(store *Store)*ExecutionRepository{return &ExecutionRepository{store:store}}

type InvoiceLineInput struct{ ContractItemID string `json:"contract_item_id"`; CurrentQuantity string `json:"current_quantity"` }
type InvoiceCreateRequest struct{ ID,ContractID,Actor,Deduction,Retention,Adjustment string; Items []InvoiceLineInput }

func number(v,field string)(float64,error){x,e:=strconv.ParseFloat(strings.TrimSpace(v),64);if e!=nil{return 0,errx.New(errx.CodeInvalidArgument,field+" must be decimal","P6-G")};return x,nil}
func fixed(v float64)string{return fmt.Sprintf("%.8f",v)}

func(r *ExecutionRepository)CreateInvoice(ctx context.Context,req InvoiceCreateRequest)(map[string]any,error){
	if req.ID==""||req.ContractID==""||req.Actor==""||len(req.Items)==0{return nil,errx.New(errx.CodeInvalidArgument,"required invoice fields are missing","P6-G")}
	var status string;if e:=r.store.db.QueryRowContext(ctx,`SELECT status FROM contracts_v2 WHERE id=?`,req.ContractID).Scan(&status);e==sql.ErrNoRows{return nil,errx.New(errx.CodeNotFound,"contract not found","P6-G")}else if e!=nil{return nil,e};if status!="APPROVED"&&status!="LOCKED"{return nil,errx.New(errx.CodeConflict,"invoice requires approved contract","P6-G")}
	ded,_:=number(defaultString(req.Deduction,"0"),"deduction");ret,_:=number(defaultString(req.Retention,"0"),"retention");adj,_:=number(defaultString(req.Adjustment,"0"),"adjustment")
	tx,e:=r.store.db.BeginTx(ctx,nil);if e!=nil{return nil,e};defer func(){_ = tx.Rollback()}()
	var period int;if e=tx.QueryRowContext(ctx,`SELECT COALESCE(MAX(period_no),0)+1 FROM invoice_periods_v2 WHERE contract_id=?`,req.ContractID).Scan(&period);e!=nil{return nil,e}
	var previous float64;var prevText string;if e=tx.QueryRowContext(ctx,`SELECT COALESCE(SUM(CAST(current_gross AS REAL)),0) FROM invoice_periods_v2 WHERE contract_id=? AND status='APPROVED'`,req.ContractID).Scan(&prevText);e==nil{previous,_=strconv.ParseFloat(prevText,64)}
	gross:=0.0;type line struct{id string;qty,amount,pq,pa float64};lines:=[]line{}
	for i,item:=range req.Items{qty,e:=number(item.CurrentQuantity,"current_quantity");if e!=nil||qty<0{return nil,errx.New(errx.CodeInvalidArgument,"current_quantity invalid","P6-G")};var priceText,contractQtyText string;if e=tx.QueryRowContext(ctx,`SELECT unit_price,quantity FROM contract_items_v2 WHERE id=? AND contract_id=?`,item.ContractItemID,req.ContractID).Scan(&priceText,&contractQtyText);e==sql.ErrNoRows{return nil,errx.New(errx.CodeInvalidArgument,"contract_item_id not found","P6-G")}else if e!=nil{return nil,e};price,_:=strconv.ParseFloat(priceText,64);contractQty,_:=strconv.ParseFloat(contractQtyText,64);var pq,pa float64;if e=tx.QueryRowContext(ctx,`SELECT COALESCE(SUM(CAST(l.current_quantity AS REAL)),0),COALESCE(SUM(CAST(l.current_amount AS REAL)),0) FROM invoice_lines_v2 l JOIN invoice_periods_v2 p ON p.id=l.period_id WHERE p.contract_id=? AND p.status='APPROVED' AND l.contract_item_id=?`,req.ContractID,item.ContractItemID).Scan(&pq,&pa);e!=nil{return nil,e};if pq+qty>contractQty{return nil,errx.New(errx.CodeInvalidArgument,"cumulative quantity exceeds contract quantity","P6-G")};amount:=qty*price;gross+=amount;lines=append(lines,line{fmt.Sprintf("%s-%d",req.ID,i+1),qty,amount,pq,pa})}
	net:=gross-ded-ret+adj;if net<0{return nil,errx.New(errx.CodeInvalidArgument,"net payable cannot be negative","P6-G")};now:=time.Now().UTC().Format(time.RFC3339Nano);snap,_:=json.Marshal(map[string]any{"contract_id":req.ContractID,"period_no":period})
	if _,e=tx.ExecContext(ctx,`INSERT INTO invoice_periods_v2(id,contract_id,period_no,status,current_gross,previous_gross,cumulative_gross,deduction,retention,adjustment,net_payable,snapshot_json,created_by,created_at,row_version) VALUES(?,?,?,'DRAFT',?,?,?,?,?,?,?,?,?,?,1)`,req.ID,req.ContractID,period,fixed(gross),fixed(previous),fixed(previous+gross),fixed(ded),fixed(ret),fixed(adj),fixed(net),string(snap),req.Actor,now);e!=nil{return nil,e}
	for i,item:=range req.Items{l:=lines[i];if _,e=tx.ExecContext(ctx,`INSERT INTO invoice_lines_v2(id,period_id,contract_item_id,current_quantity,current_amount,previous_quantity,previous_amount,cumulative_quantity,cumulative_amount,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?)`,l.id,req.ID,item.ContractItemID,fixed(l.qty),fixed(l.amount),fixed(l.pq),fixed(l.pa),fixed(l.pq+l.qty),fixed(l.pa+l.amount),i+1);e!=nil{return nil,e}}
	if e=tx.Commit();e!=nil{return nil,e};return r.GetInvoice(ctx,req.ID)
}

func(r *ExecutionRepository)TransitionInvoice(ctx context.Context,id,target string,rowVersion int64,actor string)(map[string]any,error){target=strings.ToUpper(target);var current string;var contract string;var rv int64;if e:=r.store.db.QueryRowContext(ctx,`SELECT contract_id,status,row_version FROM invoice_periods_v2 WHERE id=?`,id).Scan(&contract,&current,&rv);e==sql.ErrNoRows{return nil,errx.New(errx.CodeNotFound,"invoice not found","P6-G")}else if e!=nil{return nil,e};if rv!=rowVersion{return nil,errx.New(errx.CodeConflict,"row version conflict","P6-G")};allowed:=map[string]map[string]bool{"DRAFT":{"SUBMITTED":true},"SUBMITTED":{"DRAFT":true,"APPROVED":true}};if !allowed[current][target]{return nil,errx.New(errx.CodeInvalidArgument,"invalid invoice transition","P6-G")};now:=time.Now().UTC().Format(time.RFC3339Nano);res,e:=r.store.db.ExecContext(ctx,`UPDATE invoice_periods_v2 SET status=?,approved_by=CASE WHEN ?='APPROVED' THEN ? ELSE approved_by END,approved_at=CASE WHEN ?='APPROVED' THEN ? ELSE approved_at END,row_version=row_version+1 WHERE id=? AND row_version=?`,target,target,actor,target,now,id,rowVersion);if e!=nil{return nil,e};n,_:=res.RowsAffected();if n!=1{return nil,errx.New(errx.CodeConflict,"row version conflict","P6-G")};return r.GetInvoice(ctx,id)}

func(r *ExecutionRepository)GetInvoice(ctx context.Context,id string)(map[string]any,error){var contract,status,current,previous,cumulative,ded,ret,adj,net,snap,actor string;var period int;var rv int64;if e:=r.store.db.QueryRowContext(ctx,`SELECT contract_id,period_no,status,current_gross,previous_gross,cumulative_gross,deduction,retention,adjustment,net_payable,snapshot_json,created_by,row_version FROM invoice_periods_v2 WHERE id=?`,id).Scan(&contract,&period,&status,&current,&previous,&cumulative,&ded,&ret,&adj,&net,&snap,&actor,&rv);e==sql.ErrNoRows{return nil,errx.New(errx.CodeNotFound,"invoice not found","P6-G")}else if e!=nil{return nil,e};return map[string]any{"id":id,"contract_id":contract,"period_no":period,"status":status,"current_gross":current,"previous_gross":previous,"cumulative_gross":cumulative,"deduction":ded,"retention":ret,"adjustment":adj,"net_payable":net,"created_by":actor,"row_version":rv,"deep_link":"/app/contracts/"+contract+"/invoices/"+id},nil}

func(r *ExecutionRepository)CreateSettlement(ctx context.Context,id,contractID,adjustment,actor string)(map[string]any,error){adj,e:=number(defaultString(adjustment,"0"),"final_adjustment");if e!=nil{return nil,e};var contractAmount string;if e=r.store.db.QueryRowContext(ctx,`SELECT contract_amount FROM contracts_v2 WHERE id=?`,contractID).Scan(&contractAmount);e==sql.ErrNoRows{return nil,errx.New(errx.CodeNotFound,"contract not found","P6-G")}else if e!=nil{return nil,e};var pending int;if e=r.store.db.QueryRowContext(ctx,`SELECT COUNT(*) FROM invoice_periods_v2 WHERE contract_id=? AND status<>'APPROVED'`,contractID).Scan(&pending);e!=nil{return nil,e};if pending>0{return nil,errx.New(errx.CodeConflict,"all invoice periods must be approved","P6-G")};var invoiced float64;if e=r.store.db.QueryRowContext(ctx,`SELECT COALESCE(SUM(CAST(current_gross AS REAL)),0) FROM invoice_periods_v2 WHERE contract_id=? AND status='APPROVED'`,contractID).Scan(&invoiced);e!=nil{return nil,e};final:=invoiced+adj;if final<0{return nil,errx.New(errx.CodeInvalidArgument,"final amount cannot be negative","P6-G")};now:=time.Now().UTC().Format(time.RFC3339Nano);_,e=r.store.db.ExecContext(ctx,`INSERT INTO settlements_v2(id,contract_id,status,contract_amount,invoiced_amount,final_adjustment,final_amount,snapshot_json,created_by,created_at,row_version) VALUES(?,?,'DRAFT',?,?,?,?,?,?,?,1)`,id,contractID,contractAmount,fixed(invoiced),fixed(adj),fixed(final),`{}`,actor,now);if e!=nil{return nil,e};return r.GetSettlement(ctx,id)}
func(r *ExecutionRepository)GetSettlement(ctx context.Context,id string)(map[string]any,error){var contract,status,a,b,c,d string;var rv int64;if e:=r.store.db.QueryRowContext(ctx,`SELECT contract_id,status,contract_amount,invoiced_amount,final_adjustment,final_amount,row_version FROM settlements_v2 WHERE id=?`,id).Scan(&contract,&status,&a,&b,&c,&d,&rv);e==sql.ErrNoRows{return nil,errx.New(errx.CodeNotFound,"settlement not found","P6-G")}else if e!=nil{return nil,e};return map[string]any{"id":id,"contract_id":contract,"status":status,"contract_amount":a,"invoiced_amount":b,"final_adjustment":c,"final_amount":d,"row_version":rv},nil}
